### ISSUE TITLE
KNN returns incorrect values unless tree is Balance()d

### ISSUE THREAD

**Issue by usedbytes** [kyroy/kdtree#6]
This might be a case of "using it wrong", but KNN does not always return the nearest neighbour(s) unless the tree is balanced before the query.

My understanding is that KNN search might be slow/not-optimal on an unbalanced tree, but should still work correctly. If this isn't the case then just adding that in the doc for KNN is likely enough.

This issue is demonstrated by the attached test program, which iteratively mutates a random tree, and makes two KNN queries against it without any modifications to the tree in-between. The first has 'k' set to some low number (`few`), and the second has 'k' set to a higher number (`many`).

I would expect the first 'k' entries in the `many` query to match the entries in the `few` query, but the `few` query often omits the closest neighbours. In the output below, you can see that the `t.KNN(p, 1)` says that a point at a distance of 14.32 is the closest, whereas `t.KNN(p, 10)` gives the correct result of 11.66. After balancing, the results are correct. The value of `few` isn't critical - in my tests, any value of k < (number of entries - 1) shows the problem, but less frequently than smaller 'k's

```
Getting 1 NNs out of 10 entries
Failure on iteration 618
KNN((186.00, 218.00), 1)
   NN 0: distance((186.00, 218.00)->(172.00, 215.00)) = 14.32
KNN((186.00, 218.00), 10)
   NN 0: distance((186.00, 218.00)->(176.00, 212.00)) = 11.66
   NN 1: distance((186.00, 218.00)->(172.00, 215.00)) = 14.32
   NN 2: distance((186.00, 218.00)->(206.00, 196.00)) = 29.73
   NN 3: distance((186.00, 218.00)->(214.00, 188.00)) = 41.04
   NN 4: distance((186.00, 218.00)->(218.00, 253.00)) = 47.42
   NN 5: distance((186.00, 218.00)->(269.00, 176.00)) = 93.02
   NN 6: distance((186.00, 218.00)->(276.00, 181.00)) = 97.31
   NN 7: distance((186.00, 218.00)->(279.00, 264.00)) = 103.75
   NN 8: distance((186.00, 218.00)->(287.00, 244.00)) = 104.29
   NN 9: distance((186.00, 218.00)->(299.00, 205.00)) = 113.75
After balance:
KNN((186.00, 218.00), 1)
   NN 0: distance((186.00, 218.00)->(176.00, 212.00)) = 11.66
KNN((186.00, 218.00), 10)
   NN 0: distance((186.00, 218.00)->(176.00, 212.00)) = 11.66
   NN 1: distance((186.00, 218.00)->(172.00, 215.00)) = 14.32
   NN 2: distance((186.00, 218.00)->(206.00, 196.00)) = 29.73
   NN 3: distance((186.00, 218.00)->(214.00, 188.00)) = 41.04
   NN 4: distance((186.00, 218.00)->(218.00, 253.00)) = 47.42
   NN 5: distance((186.00, 218.00)->(269.00, 176.00)) = 93.02
   NN 6: distance((186.00, 218.00)->(276.00, 181.00)) = 97.31
   NN 7: distance((186.00, 218.00)->(279.00, 264.00)) = 103.75
   NN 8: distance((186.00, 218.00)->(287.00, 244.00)) = 104.29
   NN 9: distance((186.00, 218.00)->(299.00, 205.00)) = 113.75

```

Code follows:
```go
package main

import (
	"fmt"
	"math"
	"math/rand"
	"time"

	"github.com/kyroy/kdtree"
	"github.com/kyroy/kdtree/points"
)

func distance(a, b *points.Point2D) float64 {
	return math.Sqrt(math.Pow(a.X - b.X, 2) + math.Pow(a.Y - b.Y, 2))
}

func dumpNNs(p kdtree.Point, nns []kdtree.Point) {
	p2d1 := p.(*points.Point2D)
	fmt.Printf("KNN((%3.2f, %3.2f), %d)\n", p2d1.X, p2d1.Y, len(nns))

	for i, n := range nns {
		p2d2 := n.(*points.Point2D)
		fmt.Printf("   NN %d: distance((%3.2f, %3.2f)->(%3.2f, %3.2f)) = %3.2f\n",
			i, p2d1.X, p2d1.Y, p2d2.X, p2d2.Y, distance(p2d1, p2d2))
	}
}

func main() {
	w, h := 300, 300
	maxSize := 10
	maxTime := time.Minute

	t := kdtree.New([]kdtree.Point{})
	arr := make([]kdtree.Point, 0, maxSize)

	many := maxSize
	few := maxSize - 1

	for ; few > 0; few-- {
		fmt.Printf("Getting %d NNs out of %d entries\n", few, maxSize)
		start := time.Now()
		for i := 0; ; i++ {
			p := &points.Point2D{
				X: float64(rand.Intn(w / 2) + w / 2),
				Y: float64(rand.Intn(h / 2) + h / 2),
			}

			// Two KNN queries
			fewNN := t.KNN(p, few)
			manyNN := t.KNN(p, many)

			// Check if the nearest is the same
			if len(fewNN) > 0 {
				if distance(p, fewNN[0].(*points.Point2D)) >
					distance(p, manyNN[0].(*points.Point2D)) {
					fmt.Println("Failure on iteration", i)
					dumpNNs(p, fewNN)
					dumpNNs(p, manyNN)

					// Balance the tree and try again
					t.Balance()
					fmt.Println("After balance:")
					fewNN = t.KNN(p, few)
					manyNN = t.KNN(p, many)
					dumpNNs(p, fewNN)
					dumpNNs(p, manyNN)

					break
				}
			}

			// Add in the new point
			arr = append(arr, p)
			//fmt.Printf("Insert (%3.2f, %3.2f)\n", p.X, p.Y)
			t.Insert(p)

			// Limit the max number of elements - which will also
			// introduce some churn in the tree
			if len(arr) > maxSize {
				idx := rand.Intn(len(arr))
				//fmt.Printf("Remove (%3.2f, %3.2f)\n", p.X, p.Y)
				t.Remove(arr[idx])
				p = arr[idx].(*points.Point2D)
				arr[idx] = arr[len(arr)-1]
				arr = arr[:len(arr)-1]
			}

			if since := time.Since(start); since > maxTime {
				fmt.Printf("No failure after %d iterations (%v)\n", i, since)
				break
			}
		}
		fmt.Println("================================================")
		t.Balance()
	}
}
```

**Comment by kyroy** [comment]
Hi @usedbytes, 

Thank you for the very detailed description. It has been some time since I worked on the project. If I remember correctly, it should still return the correct neighbours.

Within the next days, I will hopefully have the time to look deeper into the problem.

**Comment by usedbytes** [comment]
Hi, ok thanks for the confirmation. My suspicion is that it's related to node removal.

I'm happy to have a go at debugging further and trying to fix this. I'm planning to take a closer look this evening. Now that I've got an isolated reproducer, I think I should be able to narrow it down to a specific tree change

**Comment by usedbytes** [comment]
I got a compact reproducer and dumped the trees. The image shows the tree before the red node is removed, and then the tree after the red node is removed.
![remove_invalid](https://user-images.githubusercontent.com/4460775/74384984-61664600-4dea-11ea-935f-b05567710842.png)
You can see that after removal, the left-most leaf has a larger 'Y' value (green) than its parent (blue), however its parent should be indexing on 'Y'.

I hope the fix in the pull request is the correct thing to do, it does seem to fix the issue. I added my specific test-case and a randomised one. They fail without the fix and pass with it.
