### ISSUE TITLE
Can't reach Data of the point returned by KNN search points array

### ISSUE THREAD

**Issue by mkadirtan** [kyroy/kdtree#8]
```
tree := new(kdtree.KDTree)
for i := 0; i < length; i++ {
	R, G, B, _ := img.At(0, i).RGBA()
	tree.Insert(points.NewPoint([]float64 {
		float64(R),
		float64(G),
		float64(B)}, Data{Value: i}))
}
```
I have built my KDTree with the above code.
When I perform a KNN search, returned points don't have the "Data" interface.
Using fmt.Println() shows related data in the console, however point.Data is impossible to use.

**Comment by kyroy** [comment]
Hello @mkadirtan,

it would be nice to see how you are trying to access the data. When receiving a result from e.g. a KNN search, you need to cast the result to the type that you expect.
```go
res := tree.KNN(...)
p := res[0].(kdtree.Point)
```

If you can show us a small example of what you are trying to achieve with a playground link, this would also help a lot, e.g. https://play.golang.org/p/CypfXqudn1V

Thanks,
Kyroy

**Comment by mkadirtan** [comment]
Hi @kyroy,
Thanks for the quick reply. Here is a demonstration of my problem:
https://play.golang.org/p/TwvZGBsEdWe

**Comment by mkadirtan** [comment]
Here is my PR for the fix: https://github.com/kyroy/kdtree/pull/9

**Comment by kyroy** [comment]
> Hi @kyroy,
> Thanks for the quick reply. Here is a demonstration of my problem:
> https://play.golang.org/p/TwvZGBsEdWe

To keep the library generic, it can only return the interface. Since you put specific data into the tree, you. can cast the interface to the specific type.
I adapted your example: https://play.golang.org/p/tqcAeoPHWaq

**Comment by mkadirtan** [comment]
> To keep the library generic, it can only return the interface. Since you put specific data into the tree, you. can cast the interface to the specific type.
I adapted your example: https://play.golang.org/p/tqcAeoPHWaq

I get the following error when I try to create an interface around the Data type:

" (type interface {} is interface with no methods) "
Here is the playground: https://play.golang.org/p/2u28X-0UzPf

**Comment by mkadirtan** [comment]
> > Hi @kyroy,
> > Thanks for the quick reply. Here is a demonstration of my problem:
> > https://play.golang.org/p/TwvZGBsEdWe
> 
> To keep the library generic, it can only return the interface. Since you put specific data into the tree, you. can cast the interface to the specific type.
> I adapted your example: https://play.golang.org/p/tqcAeoPHWaq

I understand that you are concerned about keeping the library generic, and I agree with that. However, I think KNN should be returning pointer instead of a new point. Maybe it is my lack of golang.
Anyways, here is a better demonstration: https://play.golang.org/p/cqRh4m5JyQ1

**Comment by kyroy** [comment]
> I understand that you are concerned about keeping the library generic, and I agree with that. However, I think KNN should be returning pointer instead of a new point. Maybe it is my lack of golang.
> Anyways, here is a better demonstration: https://play.golang.org/p/cqRh4m5JyQ1

https://play.golang.org/p/Ywl9XnHuvb0

KNN returns the same data that you put into the tree. You can see it in the output that you added:
```go
fmt.Println(reflect.TypeOf(results[0]))
// *main.mypoint
```
It even returns the same pointer. Your pointer output was creating 2 new pointers and printing these. I fixed it in the updated link.

**Comment by mkadirtan** [comment]
> > I understand that you are concerned about keeping the library generic, and I agree with that. However, I think KNN should be returning pointer instead of a new point. Maybe it is my lack of golang.
> > Anyways, here is a better demonstration: https://play.golang.org/p/cqRh4m5JyQ1
> 
> https://play.golang.org/p/Ywl9XnHuvb0
> 
> KNN returns the same data that you put into the tree. You can see it in the output that you added:
> 
> fmt.Println(reflect.TypeOf(results[0]))
> // *main.mypoint
> It even returns the same pointer. Your pointer output was creating 2 new pointers and printing these. I fixed it in the updated link.

Yep, thanks for the replies. After all these years, I've finally learned Go properly and understood my mistake 😄
